<?php
/**
 * Created by PhpStorm.
 * User: reals
 * Date: 7/7/2017
 * Time: 12:01 AM
 */
class GerejaCustom extends Gereja
{
    public function rules()
    {
        $defaultRule = parent::rules();
        $newRule = array(
//            array('no_polisi', 'uniqueNopol'),
        );

        return array_merge($defaultRule, $newRule);
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}