<?php
/**
 * Created by PhpStorm.
 * User: reals
 * Date: 7/8/2017
 * Time: 12:19 PM
 */
class HistoryGerejaViewCustom extends HistoryGerejaView
{
    public function rules()
    {
        $defaultRule = parent::rules();
        $newRule = array(
//            array('no_polisi', 'uniqueNopol'),
        );

        return array_merge($defaultRule, $newRule);
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getTopViewedChurches() {
        $hasil = array();
        $sql="
        select g.nama, hgv2.gereja_id
        from (
        select hgv.gereja_id, count(gereja_id) seen
        from history_gereja_view hgv
        group by hgv.gereja_id
        order by seen desc
        limit 5 ) hgv2 
        left join gereja g on g.id = hgv2.gereja_id
        ";
        $command = Yii::app()->db->createCommand($sql);
        $topList = $command->queryAll();

        foreach($topList as $setiap) {
            //echo "<pre>";var_dump($setiap);die;
            $gereja = array(
                'gereja_id' => $setiap['gereja_id'],
                'nama'=> $setiap['nama'],
                'gambar'=> Yii::app()->baseUrl.'/images/gerejas/'.HistoryGerejaViewCustom::getPicForCarousel($setiap['gereja_id'])
            );
            array_push($hasil, $gereja);
        }
        return $hasil;
    }

    public static function getPicForCarousel($gereja_id) {
        $sql ="
        select * from foto_gereja
        where gereja_id = :idGereja
        limit 1
        ";
        $data = Yii::app()->db->createCommand($sql);
        $data->bindValue(':idGereja',$gereja_id);
        $rawData = $data->queryAll();
        if($rawData) {
            return $rawData[0]['nama_foto'];
        } else {
            return 'kosong';
        }
    }
}